[variables]
NODE_VERSION = "20.18.0"
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci --quiet"]

[phases.build]  
cmds = ["npm run build:railway"]

[start]
cmd = "node index-railway-minimal.js"