[variables]
NODE_VERSION = "22.11.0"
NODE_ENV = "production"
PORT = "3003"

[phases.install]
cmds = ["npm ci --quiet"]

[phases.build]  
cmds = ["npm run build:railway"]

[start]
cmd = "node index-ultra-minimal.js"