[build]
builder = "NIXPACKS"

[variables]
NODE_VERSION = "22.12.0"

[phases.install]
cmds = ["npm install --no-audit --no-fund --legacy-peer-deps --no-workspaces"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "npm start"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"