# CI/CD Pipeline for AlexIQ
name: CI/CD Pipeline

on:
  push:
    branches: [main, minimal-prod]
  pull_request:
    branches: [main, minimal-prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node 22.16
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
            
      - name: Install Dependencies
        run: npm install --no-audit --no-fund --legacy-peer-deps
        
      - name: Build Project
        run: npm run build --if-present
        
      - name: Test Project
        run: npm test --if-present