# CI/CD Pipeline for HustleFinder Alex IQ
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "22.12.0"

jobs:
  # Build and Test
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci --no-audit --no-fund

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci --no-audit --no-fund

      - name: Build Backend
        working-directory: backend
        run: npm run build --if-present

      - name: Build Frontend
        working-directory: frontend
        run: npm run build --if-present

      - name: Test Backend
        working-directory: backend
        run: |
          npm test || echo "No test script found"

      - name: Test Frontend
        working-directory: frontend
        run: |
          npm test || echo "No test script found"