# CI/CD Pipeline for AlexIQ
name: CI/CD Pipeline

on:
  push:
    branches: [main, minimal-prod]
  pull_request:
    branches: [main, minimal-prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node 22.12
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.x'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json
            
      - name: Install Backend
        working-directory: backend
        run: npm install --no-audit --no-fund --legacy-peer-deps --no-workspaces
        
      - name: Build Backend
        working-directory: backend
        run: npm run build --if-present
        
      - name: Install Frontend
        working-directory: frontend
        run: npm install --no-audit --no-fund --legacy-peer-deps --no-workspaces
        
      - name: Build Frontend
        working-directory: frontend
        run: npm run build
        
      - name: Test Backend
        working-directory: backend
        run: npm test --if-present
        
      - name: Test Frontend  
        working-directory: frontend
        run: npm test --if-present