# CI/CD Pipeline for AlexIQ
name: CI/CD Pipeline

on:
  push:
    branches: [main, minimal-prod]
  pull_request:
    branches: [main, minimal-prod]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node 22.16
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.x'
          cache: 'npm'
            
      - name: Install Dependencies
        run: |
          npm install --no-audit --no-fund
          cd backend && npm install --no-audit --no-fund
          cd ../frontend && npm install --no-audit --no-fund
        
      - name: Check Backend
        run: cd backend && node -e "console.log('Backend check OK')"
        
      - name: Check Frontend Build
        run: cd frontend && npm run build
        
      - name: Verify Build Output
        run: ls -la frontend/dist