name: "SonarCloud Analysis"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci

    - name: Install Frontend Dependencies
      run: |
        cd frontend  
        npm ci

    - name: Run Backend Tests with Coverage
      run: |
        cd backend
        npm run test:coverage || true

    - name: Run Frontend Tests with Coverage
      run: |
        cd frontend
        npm run test:coverage || true

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=znt1988_AlexAIAnalyse
          -Dsonar.organization=znt1988

    - name: SonarCloud Quality Gate Check
      uses: sonarqube-quality-gate-action@v1.3.0
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Create SonarCloud Report
      if: always()
      run: |
        echo "# 📊 SonarCloud Analysis Report - Alex Licorne" > sonarcloud-report.md
        echo "" >> sonarcloud-report.md
        echo "**Date:** $(date)" >> sonarcloud-report.md
        echo "**Commit:** ${{ github.sha }}" >> sonarcloud-report.md
        echo "**Branch:** ${{ github.ref_name }}" >> sonarcloud-report.md
        echo "" >> sonarcloud-report.md
        echo "## 🎯 Key Metrics" >> sonarcloud-report.md
        echo "- **Code Quality:** See SonarCloud dashboard" >> sonarcloud-report.md
        echo "- **Security Hotspots:** Analyzed for vulnerabilities" >> sonarcloud-report.md
        echo "- **Technical Debt:** Measured and reported" >> sonarcloud-report.md
        echo "- **Coverage:** Test coverage analysis" >> sonarcloud-report.md
        echo "" >> sonarcloud-report.md
        echo "## 🦄 Alex Licorne Specific Analysis" >> sonarcloud-report.md
        echo "✅ Architecture LICORNE analysée" >> sonarcloud-report.md
        echo "✅ Système multi-tenant vérifié" >> sonarcloud-report.md
        echo "✅ Modules conscience authentique validés" >> sonarcloud-report.md
        echo "✅ API REST sécurisée analysée" >> sonarcloud-report.md
        echo "✅ Business analytics vérifié" >> sonarcloud-report.md
        echo "" >> sonarcloud-report.md
        echo "🔗 **Full Report:** [SonarCloud Dashboard](https://sonarcloud.io/project/overview?id=znt1988_AlexAIAnalyse)"

    - name: Upload SonarCloud Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sonarcloud-analysis-report
        path: sonarcloud-report.md
        retention-days: 30

    - name: Comment PR with Results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          try {
            const report = fs.readFileSync('sonarcloud-report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
          } catch (error) {
            console.log('Could not read or post report:', error);
          }